Play travis
Otus-DevOps-2023-05/ba0babus_infra pull request #1
Opened 2023-06-20 06:06 UTC by ba0babus

Установил pre-commit, сделал aciton, поправил test.py

2023-06-20 19:27 UTC, mrgreyves requested changes
Здравствуйте!
Оставил комментарий к файлу
ДЗ возвращаю на доработку

2023-06-20 19:27 UTC, mrgreyves commented on .github/auto-assign.yml
> +# Set to true to add assignees to pull requests
Переименуйте файл в auto_assign.yml

2023-06-21 09:33 UTC, ba0babus commented
Здравствуйте, поправил)

2023-06-25 12:44 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь все круто =)

2023-07-06 07:57 UTC, merged